XNAT-2985: Added expanded handling of Throwables, as some lower-level problems (e.g. NoClassDefFoundError) were getting lost. Updated to version 1.6.4-SNAPSHOT.